// playground/solid-vite/src/components/Button.tsx
import { mergeStyle } from '@kaze-style/core';
import type { Component, JSX } from 'solid-js';
import { classes } from './Button.style';

export const Button: Component<JSX.IntrinsicElements['button']> = (props) => {
  return <button {...props} class={mergeStyle(classes.$button, props.class)} />;
};

// playground/next/src/components/Button.tsx
import { mergeStyle } from '@kaze-style/core';
import type { ComponentProps, FC } from 'react';
import { classes } from './Button.style';

export const Button: FC<ComponentProps<'button'>> = (props) => {
  return (
    <button
      {...props}
      className={mergeStyle(classes.$button, props.className)}
    />
  );
};
